### PR TITLE
Allow to search without accent

### PR DESCRIPTION
**Pull request by Joozty**
Closes https://github.com/oacore/next/issues/9

### CODE REVIEW

**Comment by viktor-yakubiv** [comment]
It's quite interesting. I tested search before and typing things with or without accents worked. I wondered that you used normalisation so I explored whole library to find accent thing and I did not. So I assume actual search with accents worked just because fuzzy search algorithm which may ignore a character or a few to improve search.

**Comment by Joozty** [comment]
Strange it didn't work for me. It also may use your browser localization and hence some search may work for you and not for me. I am just guessing I didn't explore the library. Do you have your browser in Ukrainian?

Anyway, you ok with this PR. Can it be merged and deployed? 🙂

**Comment by viktor-yakubiv** [comment]
@Joozty would you like to review?

**Comment by Joozty** [comment]
It's alright. I already had a look.

**Pull request merged**
