### PR TITLE
Crop white space in image

### PR DESCRIPTION
**Pull request by Joozty**
The reason for it is that the image looks better on small screens

### CODE REVIEW

**Comment by viktor-yakubiv** [comment]
It's better on the small screens but worse on the large screens. Is it possible to limit max-height to actual pixels size and max-width to 100% there?

**Comment by Joozty** [comment]
Do you mean styles in this page https://next-git-image.oacore.vercel.app/documentation/discovery/plugin/ or in the dashboard one?

**Comment by viktor-yakubiv** [comment]
Yes, I know, it's markdown so you will need to convert it to an HTML `` with the `style` attribute.

**Comment by Joozty** [comment]
But the image already uses the correct height the styles applied there are max-width: 100% and height: auto which results to correct pixel height of 148px

**Comment by Joozty** [comment]
What about this? I see the following options:

1. keep it as is
2. load different images according to screen resolution
3.  close it

**Comment by viktor-yakubiv** [comment]
The screenshot is taken on the retina display so it's doubled (quadrupled, 2x width, 2x height) so it looks unnatural if passed as is. The actual image height is `74px`. Could you please pass `style="max-height: 74px"` to it and merge?

**Pull request merged**
