### PR TITLE
Update David's description.

### PR DESCRIPTION
**Pull request by hanana1**

### CODE REVIEW

**Comment by viktor-yakubiv** [comment]
This needs to be edited. It fits BSDTAg website but doesn't fit CORE. Here, it should be more related to CORE and perhaps a bit more formal.

**Review by viktor-yakubiv — CHANGES_REQUESTED** [review]
Maybe I will have a look at this later

**Comment by viktor-yakubiv** [comment]
@hanana1 how the current text looks to you?

**Comment by hanana1** [comment]
> @hanana1 how the current text looks to you?

For me - fine. I just copied what David texted me. Let's publish, I'll ask his opinion after.

**Pull request merged**
