### PR TITLE
Use css modules

### PR DESCRIPTION
**Pull request by Joozty**

### CODE REVIEW

**Comment by Joozty** [comment]
@viktor-yakubiv This is how far I got. [The remaining components](https://github.com/oacore/next/blob/modules/components/index.scss#L3-L6) are hard to migrate it would need more refactor.  Also this PR didn't help with the hard refresh. So we may not need to merge it really. On the other hand  it can help us with migration to @oacore/design.


PS: I probably broke too many things. 😄

**Comment by viktor-yakubiv** [comment]
@Joozty can you please rebase the branch fixing the conflicts?

**Comment by viktor-yakubiv** [comment]
1. Testimonial sections on the home page lost border. The first of them
2. **⏳ to be continued...**

**Review by viktor-yakubiv — APPROVED** [review]
Please, fix the first remark.

**Pull request merged**
