### PR TITLE
Fix applying polyfills

### PR DESCRIPTION
**Pull request by Joozty**
Causes hard refresh on any change. @viktor-yakubiv I hope we don't need this polyfill. If we do I will find another solution. Let me know. :)

### CODE REVIEW

**Comment by viktor-yakubiv** [comment]
FormData was needed to support settigns at core.ac.uk/cookies in IE 11 (only). Please, check the analytics, if IE is not there, feel free to remove.

Also, could you please update the local browsersconfig file with the most recent stats?

**Comment by viktor-yakubiv** [comment]
> Also, could you please update the local browsersconfig file with the most recent stats?

If you think this is not a good idea, please remove the file and setup browsersconfig to global.

**Review by viktor-yakubiv — APPROVED** [review]
Wow! Does it work so? Does it fixes the problem?

**Comment by Joozty** [comment]
IE 11 is still quite used (about 0.7%our users use it) so I came up with a different solution based on [an official example](https://github.com/vercel/next.js/tree/canary/examples/with-polyfills).



> Also, could you please update the local browsersconfig file with the most recent stats?
I don't know how should I update it? How did you generate it?

**Comment by viktor-yakubiv** [comment]
It's awesome! Thank you! 👍

**Pull request merged**
